name: Generate Pages

env:
  CI: true
  FORCE_COLOR: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "*/15 * * * *"

jobs:
  lqty-supply:
    name: Generate LQTY Circulating Supply File
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Node v12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Set Yarn cache dir
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore Yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Fetch LQTY circulating supply
        run: yarn once
        env:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

      - name: Commit generated files
        uses: EndBug/add-and-commit@v7.2.1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          message: "chore: update LQTY circulating supply"
          add: docs
          pull_strategy: NO-PULL
          push: --force origin HEAD:pages
